[project]
name = "velocitas_lib"
version = "0.0.2"
dependencies = [
    "requests >= 2.31.0",
    "types-requests"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
